from nodes import VarDecl, OutStmt, RunStmt, FuncDef

def generate_bash(nodes) -> str:
    lines = []
    # Header logic
    if not hasattr(generate_bash, 'called'):
         if any(isinstance(n, (VarDecl, OutStmt, RunStmt, FuncDef)) for n in nodes):
             lines.append("#!/bin/sh")
             lines.append("# Generated by bashDSL (she's beautiful 💅)")
             generate_bash.called = True

    for node in nodes:
        if isinstance(node, VarDecl):
            prefix = "local " if node.is_local else ""
            val = f"${node.value}" if node.is_ref else node.value
            lines.append(f"{prefix}{node.name}={val}")
        
        elif isinstance(node, OutStmt):
            val = f"${node.value}" if node.is_ref else node.value
            lines.append(f"echo {val}")
        
        elif isinstance(node, RunStmt):
            args = []
            if node.arg_is_ref:
                for arg, is_ref in zip(node.args, node.arg_is_ref):
                    args.append(f"${arg}" if is_ref else arg)
            else:
                args = node.args
            lines.append(f"{node.executable} {' '.join(args)}")
        
        elif isinstance(node, FuncDef):
            lines.append(f"{node.name}() {{")
            for i, arg in enumerate(node.args):
                lines.append(f"  local {arg}=\"${i+1}\"")
            
            old_called = getattr(generate_bash, 'called', False)
            generate_bash.called = True 
            body_code = generate_bash(node.body)
            generate_bash.called = old_called
            
            for line in body_code.split('\n'):
                if line:
                    lines.append(f"  {line}")
            lines.append("}")
    
    return "\n".join(lines)
