from nodes import VarDecl, OutStmt, RunStmt, FuncDef, ClassDef, Comment

def generate_bash(nodes) -> str:
    lines = []
    globals_to_unset = []
    # Header logic
    if not hasattr(generate_bash, 'called'):
         lines.append("#!/bin/sh")
         lines.append("# Generated by bashDSL (Restructured 💅)")
         generate_bash.called = True

    for node in nodes:
        if isinstance(node, Comment):
            if node.multi_line:
                for comment_line in node.value.split('\n'):
                    lines.append(f"# {comment_line.strip()}")
            else:
                lines.append(f"# {node.value}")
        
        elif isinstance(node, VarDecl):
            prefix = "local " if node.is_local else ""
            if not node.is_local:
                globals_to_unset.append(node.name)
            if node.is_pub and not node.is_local:
                lines.append(f"# Public Variable: {node.name}")
            val = f"${node.value}" if node.is_ref else node.value
            lines.append(f"{prefix}{node.name}={val}")
        
        elif isinstance(node, OutStmt):
            args = []
            for val, is_ref in zip(node.values, node.refs):
                args.append(f"${val}" if is_ref else val)
            
            # 🏁 Redirection Logic (The Stream Choice)
            if len(node.values) >= 2:
                stream = node.values[1] # Check the raw value (with quotes)
                if stream == '"stdout"':
                    # Yeet the stream arg and echo normally
                    args.pop(1)
                    lines.append(f"echo {' '.join(args)}")
                elif stream == '"stderr"':
                    # Yeet the stream arg and redirect to stderr
                    args.pop(1)
                    lines.append(f"echo {' '.join(args)} >&2")
                else:
                    lines.append(f"echo {' '.join(args)}")
            else:
                lines.append(f"echo {' '.join(args)}")
        
        elif isinstance(node, RunStmt):
            args = []
            if node.arg_is_ref:
                for arg, is_ref in zip(node.args, node.arg_is_ref):
                    args.append(f"${arg}" if is_ref else arg)
            else:
                args = node.args
            lines.append(f"{node.executable} {' '.join(args)}")
        
        elif isinstance(node, FuncDef):
            if node.is_pub:
                lines.append(f"# Public Function: {node.name}")
            lines.append(f"{node.name}() {{")
            for i, arg in enumerate(node.args):
                lines.append(f"  local {arg}=\"${i+1}\"")
            
            old_called = getattr(generate_bash, 'called', False)
            generate_bash.called = True 
            body_code = generate_bash(node.body)
            generate_bash.called = old_called
            
            for body_line in body_code.split('\n'):
                if body_line: lines.append(f"  {body_line}")
            lines.append("}")

    # 🧹 Cleanup Phase: Unset globals at the very end
    if globals_to_unset:
        lines.append("# Cleanup: Localizing script-level variables")
        for name in globals_to_unset:
            lines.append(f"unset {name}")
    
    return "\n".join(lines)
